version: 1.0.{build}
image: Visual Studio 2017
install:
  - dotnet tool install -g Cake.Tool --version 0.31.0 
  - cinst msbuild-sonarqube-runner
build_script:
- cmd: >-
    dotnet cake -Target=CreateArtifact -buildConfig=Release

    dotnet cake --Host="Rider" -Target=CreateArtifact -buildConfig=Release

    SonarQube.Scanner.MSBuild.exe begin /k:"resharper-configuration-sense" /d:"sonar.organization=olsh-github" /d:"sonar.host.url=https://sonarcloud.io" /d:"sonar.login=J5oiVp07l1PkxuTJIFyD142+AuOMcVNLZIXpUsF3UCEz3Jjn6bALMSbaQdF8TA33" /v:"$env:APPVEYOR_BUILD_VERSION" /n:"Configuration Sense"

    MsBuild.exe /t:Rebuild /v:q src\Resharper.ConfigurationSense.sln

    SonarQube.Scanner.MSBuild.exe end /d:"sonar.login=J5oiVp07l1PkxuTJIFyD142+AuOMcVNLZIXpUsF3UCEz3Jjn6bALMSbaQdF8TA33"
test: off
cache:
  - '%USERPROFILE%\.sonar\cache'
  - '%USERPROFILE%\.nuget\packages -> **\*.csproj'
  - 'tools -> build.cake'
